services:
  arvosana:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  migrate:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./db/migrations:/migrations
    command: -path=/migrations -database=sqlite3://${DB} up
