// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: homework.sql

package db

import (
	"context"

	"github.com/is1ab/Arvosana/types"
)

const addHomework = `-- name: AddHomework :exec
INSERT INTO homework (name, semester, deadline)
VALUES (?, ?, ?)
`

type AddHomeworkParams struct {
	Name     string
	Semester types.Semester
	Deadline types.Datetime
}

func (q *Queries) AddHomework(ctx context.Context, arg AddHomeworkParams) error {
	_, err := q.db.ExecContext(ctx, addHomework, arg.Name, arg.Semester, arg.Deadline)
	return err
}

const getAllHomeworks = `-- name: GetAllHomeworks :many
SELECT name, semester, deadline FROM homework
`

type GetAllHomeworksRow struct {
	Name     string
	Semester types.Semester
	Deadline types.Datetime
}

func (q *Queries) GetAllHomeworks(ctx context.Context) ([]GetAllHomeworksRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllHomeworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllHomeworksRow
	for rows.Next() {
		var i GetAllHomeworksRow
		if err := rows.Scan(&i.Name, &i.Semester, &i.Deadline); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
