// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/is1ab/Arvosana/types"
)

type Homework struct {
	ID        int64
	Name      string
	CreatedAt types.Datetime
	Deadline  types.Datetime
}

type Student struct {
	ID        int64
	StudentID string
	Semester  types.Semester
}

type StudentGrade struct {
	StudentID  int64
	HomeworkID int64
	Grade      int64
}
