// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"
)

type Homework struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	Deadline  time.Time
}

type Student struct {
	ID       string
	Semester string
}

type StudentGrade struct {
	StudentID  string
	HomeworkID int64
	Grade      int64
}
