// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: student.sql

package db

import (
	"context"
)

const addStudent = `-- name: AddStudent :exec
INSERT INTO student (id, semester)
VALUES (?, ?)
`

type AddStudentParams struct {
	ID       string
	Semester string
}

func (q *Queries) AddStudent(ctx context.Context, arg AddStudentParams) error {
	_, err := q.db.ExecContext(ctx, addStudent, arg.ID, arg.Semester)
	return err
}
